[tool.poetry]
name = "hotpepper-gourmet"
version = "0.0.0" # use poetry-dynamic-versioning
description = "A simple Python client of Hotpepper API"
authors = ["paperlefthand <being.paperlefthand@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/paperlefthand/hotpepper-gourmet"
keywords = ["hotpepper", "api", "client"]
classifiers = [
#     "Programming Language :: Python :: Implementation :: CPython",
     "Programming Language :: Python :: 3",
     "Operating System :: OS Independent",
#     "Topic :: Software Development :: Libraries :: Python Modules",
#     "Intended Audience :: Developers",
]
packages = [
    { include = "pygourmet"},
]
# homepage = 

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32"
types-requests = "^2.32.0.20240712"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2"
pytest-cov = "^5.0.0"
# pytest-testinfra = "^7.0"
# responses = "^0.22"
# black = "^23.1.0"
ruff = "^0.5.3"
# sphinx-rtd-theme = "^1.2.0"
# sphinx-fontawesome = "^0.0.6"
# myst-parser = "^1.0.0"
# sphinx-autobuild = "^2021.3.14"
requests-mock = "^1.12.1"

[tool.poetry-dynamic-versioning]
enable = true
style = "pep440"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
