; NOTE English only
[tox]
requires = tox>=4.20, tox-uv>=1.28
env_list = lint,format,type,py3.12,py3.13,py3.14

[testenv]
; NOTE Required to skip local-only tests in tox environment
; passenv = GITHUB_ACTIONS
runner = uv-venv-runner
; NOTE uv-venv-lock-runner is not recommended in library development
description = Run tests
dependency_groups = dev, test
commands = pytest -n auto --maxfail=1 -q --tb=short --no-header

[testenv:lint]
skip_install = true
dependency_groups = dev
commands = ruff check .

[testenv:format]
skip_install = true
dependency_groups = dev
commands =
    ruff check . --fix
    ruff format .

[testenv:type]
skip_install = true
dependency_groups = dev
commands = ty check src/pygourmet
