; NOTE English only
[tox]
requires = tox>=4.20, tox-uv>=1.28
env_list = lint,format,type,py311,py312,py313,docs

[testenv]
; NOTE Required to skip local-only tests in tox environment
; passenv = GITHUB_ACTIONS
description = Run tests
dependency_groups = dev, test
commands = pytest -n auto -v --maxfail=1

[testenv:lint]
skip_install = true
dependency_groups = dev
commands = ruff check .

; [testenv:format]
; skip_install = true
; dependency_groups = dev
; commands = ruff format --check .

[testenv:format]
skip_install = true
dependency_groups = dev
commands =
    ruff check . --fix
    ruff format .

[testenv:type]
skip_install = true
dependency_groups = dev, test
commands = ty check

[testenv:docs]
dependency_groups = dev, doc
commands = sphinx-build -b html docs docs/_build/html
