name: deploy

on:
  push:
    branches:
      - "main"

jobs:
  pytest:
    uses: paperlefthand/hotpepper-gourmet/.github/workflows/pytest.yml@main

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: poetry build
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
