name: deploy

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    name: Test, Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Define a cache for the virtual environment based on the dependencies lock file
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}        
      - name: Install Dependencies
        run: poetry install --no-interaction
      - name: Run Tests
        env:
          KEYID: ${{ secrets.KEYID }}
        run: poetry run pytest -v
      - name: Build
        run: poetry build
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
